### ISSUE TITLE
Consider Micropy

### ISSUE THREAD

**Issue by jduckles** [annefou/IoT_introduction#3]
I don't want to derail the work you've already done, but I wanted to point out that I've found [micropython](https://micropython.org/) to be a very good firmware to to run on the ESP8266 IoT devices. 

Yes, you have to flash the firmware, but it has the advantage of sticking to similar python syntax that is taught in a bunch of other places and giving researchers the ability to program a microcontroller in a syntax they may already know. 

## Pros:
* Python on your microcontroller! 
* Can build on other concepts from learning to script python `boot.py` and `main.py` startup 
* Less sytnaxes to keep in your head

## Cons: 
* Not integrated to the Arduino IDE (as far as I know)
* Requires a couple of CLI tools

Anyway just my $0.02, like I said, not trying to derail your already work done, just bringing other considerations. It looks great so-far.

**Comment by annefou** [comment]
Very good point. And it does not at all deviate from the work we already done. In fact my very first thought was to write the tutorial using micropython for the very same reason you invoked (be closed to what we already teach in the Carpentries, etc.) and because I am using micropython too.

We changed our mind as I thought it could be too much for one short workshop (we had 1/2 day only). We decided to put very few emphasis on the programming part and avoid CLI as much as possible. So mostly focusing on using "hardware" to assemble sensors.

But I  keep it in mind for a longer workshop where CLI, python/micropython could be introduced as complementary sections/lessons.

Thanks for your comment.
